// Test generated by RoostGPT for test Java-Test using AI Type Open AI and AI Model gpt-4

package hello;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.runners.MockitoJUnitRunner;
import org.joda.time.LocalTime;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

@RunWith(MockitoJUnitRunner.class)
public class Greeter_sayTime_0bb2d8778b_Test {

    @InjectMocks
    Greeter greeter;

    @Before
    public void setup() {
        greeter = new Greeter();
    }

    @Test
    public void testSayTime_NotNull() {
        String time = greeter.sayTime();
        assertNotNull(time);
    }

    @Test
    public void testSayTime_ValidFormat() {
        String time = greeter.sayTime();
        String[] parts = time.split(":");
        assertTrue(parts.length == 3);
        assertTrue(Integer.parseInt(parts[0]) >= 0 && Integer.parseInt(parts[0]) <= 23);
        assertTrue(Integer.parseInt(parts[1]) >= 0 && Integer.parseInt(parts[1]) <= 59);
        assertTrue(Integer.parseInt(parts[2]) >= 0 && Integer.parseInt(parts[2]) <= 59);
    }
}
