// Test generated by RoostGPT for test Java-Test using AI Type Open AI and AI Model gpt-4

package hello;

import org.joda.time.LocalTime;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.*;

@RunWith(MockitoJUnitRunner.class)
public class Greeter_sayHello_26998730d5_Test {

    @Test
    public void testSayHello() {
        Greeter greeter = new Greeter();
        String result = greeter.sayHello();
        assertNotNull(result);
        assertTrue(result.startsWith("The current local time is: "));
    }

    @Test
    public void testSayHelloForSpecificTime() {
        Greeter greeter = new Greeter() {
            @Override
            public LocalTime getCurrentTime() {
                return new LocalTime(12, 0); // 12:00
            }
        };
        String result = greeter.sayHello();
        assertEquals("The current local time is: 12:00:00.000", result);
    }
}
